import { createTheme } from '@mui/material/styles';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Box } from "@mui/material";
import Footer from "@/components/footer/Footer";
import { StoreProvider } from '@/reduxconfig/StoreProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <header>
            <Navbar />
          </header>

          <main>
            <Box sx={{ marginX: "20px", marginY: "30px" }}>
              {children}
            </Box>
          </main>

          <footer>
            <Footer />
          </footer>
        </body>
      </html >
    </StoreProvider>
  );
}
